config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', include('portfolio.urls', namespace='portfolio')),
]

if settings.DEBUG:   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home, name='home'),
    path('resume/', views.resume, name='resume'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
]

portfolio/models.py
from django.db import models
from django.urls import reverse

class Resume(models.Model):
    image = models.ImageField(upload_to='resume/image/')
    name = models.CharField(max_length=50, db_index=True)
    age = models.IntegerField()
    job = models.CharField(max_length=100, db_index=True)
    email = models.EmailField(max_length=254)
    cv_file = models.FileField(upload_to='resume/files/')
    description = models.TextField()

    def __str__(self):
        return self.name


class DesignSkill(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class CodingSkill(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class LanguageSkill(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Service(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    description = models.TextField()
    icon = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.title


class Client(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='resume/clients/')

    def __str__(self):
        return self.title



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Project(models.Model):
    category = models.ForeignKey(Category , related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    description = models.TextField()
    image = models.ImageField(upload_to='portfolio/porjects/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return self.title    


class Social(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    link = models.URLField(max_length=200)
    icon = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.title   


class Message(models.Model):
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=254, null=False)
    subject = models.CharField(max_length=100, null=False)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dashboard:message_detail", args=[self.pk, self.name])
    

portfolio/forms.py
from django.forms import ModelForm, widgets
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox

from .models import Message


class MessageForm(ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'message', 'captcha']

portfolio/views.py
from django.shortcuts import redirect, render
from django.contrib import messages

from .models import (Client, 
                Resume, 
                CodingSkill, 
                DesignSkill, 
                LanguageSkill, 
                Service, 
                Category, 
                Project)
from .forms import MessageForm


def home(request):
    return render(request, 'portfolio/home.html')

def resume(request):
    user = Resume.objects.get(id=1)
    design_skills = DesignSkill.objects.all()
    coding_skills = CodingSkill.objects.all()
    languages = LanguageSkill.objects.all()
    services = Service.objects.all()
    clients = Client.objects.all()
    return render(request, 'portfolio/resume.html', {'user': user,
        'coding_skills': coding_skills,
        'design_skills': design_skills,
        'languages': languages,
        'services': services,
        'clients': clients})

def portfolio(request):
    categories = Category.objects.all()
    projects = Project.objects.all()
    return render(request, 'portfolio/portfolio.html', {'projects': projects, 'categories': categories})


def contact(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thanks, your message is sent successfully. We will contact you shortly!')
            return redirect('portfolio:contact')
    else:
        form = MessageForm()
    return render(request, 'portfolio/contact.html', {'form': form})

portfolio/templates/portfolio/contact.html
{% extends 'base.html' %}
{% load base_tags %}

{% block title %} | Contact{% endblock %}

{% block content %}
	<div class="container">
		
		<!-- Header -->
		{% include 'portfolio/partials/nav_header.html' %}
		
		<!-- Wrapper -->
		<div class="wrapper">
		
			<!-- Started -->
			<div class="section started">
				<div class="centrize full-width">
					<div class="vertical-center">
						<div class="started-content">
							{% if messages %}
								{% for message in messages %}
									<div class="alert-contact {{ message.tags }}">
										<span class="ion ion-android-checkmark-circle"></span> {{ message }}
									</div>
								{% endfor %}
							{% endif %}
							<div class="h-title glitch-effect" data-text="Contact">Contact</div>
							<div class="h-subtitle typing-bread">
								<p><a href="{% url 'portfolio:home' %}">Home</a> / <a href="{% url 'portfolio:contact' %}">Contact</a></p>
							</div>
							<span class="typed-bread"></span>
						</div>
					</div>
				</div>
				<a href="#" class="mouse_btn"><span class="ion ion-mouse"></span></a>
			</div>
			
			<!-- Contacts Info -->
			<div class="section contacts">
				<div class="content">
					<div class="title">
						<div class="title_inner">Contacts</div>
					</div>
					<div class="service-items">
						<div class="service-item">
							<div class="icon"><span class="ion ion-android-phone-portrait"></span></div>
							<div class="name">Phone</div>
							<p>
								+ (911) 877 09 20
							</p>
						</div>
						<div class="service-item">
							<div class="icon"><span class="ion ion-email"></span></div>
							<div class="name">Email</div>
							<p>
								<a href="mailto:yasinalipour01@gmail.com">yasinalipour01@gmail.com</a>
							</p>
						</div>
						<div class="service-item">
							<div class="icon"><span class="ion ion-ios-location"></span></div>
							<div class="name">Address</div>
							<p>
								Tehran, Iran
							</p>
						</div>
					</div>
					<div class="contact_form">
						<form id="cform" method="post">
							{% csrf_token %}
							{{ form.as_p }}
							<button type='submit' class="btn fill" data-text="Send Message"/>Send Message</button>
						</form>
					</div>
				</div>
			</div>
		
		</div>
		
		<!-- Footer -->
		{% social_media %}
		
	</div>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'base.html' %}
{% load base_tags %}

{% block content %}
	<div class="container">
		
		<!-- Header -->
		{% include 'portfolio/partials/nav_header.html' %}
		
		<!-- Wrapper -->
		<div class="wrapper">
		
			<!-- Started -->
			<div class="section started">
				<div class="centrize full-width">
					<div class="vertical-center">
						<div class="started-content">
							<div class="h-title glitch-effect" data-text="I'm Yasin Alipour">I'm Yasin Alipour</div>
							<div class="h-subtitle typing-subtitle">
								<p>FrontEnd Developer.</p>
								<p>Django BackEnd Developer.</p>
								<p>Based in Tehran.</p>
							</div>
							<span class="typed-subtitle"></span>
						</div>
					</div>
				</div>
			</div>
		
		</div>
		
		<!-- Footer -->
		{% social_media %}
		
	</div>
{% endblock %}

portfolio/templates/portfolio/portfolio.html
{% extends 'base.html' %}
{% load base_tags %}

{% block title %} | Portfolio{% endblock %}

{% block content %}
	<div class="container">
		
		<!-- Header -->
		{% include 'portfolio/partials/nav_header.html' %}
		
		<!-- Wrapper -->
		<div class="wrapper">
		
			<!-- Started -->
			<div class="section started">
				<div class="centrize full-width">
					<div class="vertical-center">
						<div class="started-content">
							<div class="h-title glitch-effect" data-text="Portfolio">Portfolio</div>
							<div class="h-subtitle typing-bread">
								<p><a href="{% url 'portfolio:home' %}">Home</a> / <a href="{% url 'portfolio:portfolio' %}">Portfolio</a></p>
							</div>
							<span class="typed-bread"></span>
						</div>
					</div>
				</div>
				<a href="#" class="mouse_btn"><span class="ion ion-mouse"></span></a>
			</div>
			
			<!-- Works -->
			<div class="section works">
				<div class="content">

					<div class="filter-menu">
						<div class="filters">
							{% if projects %}
								<div class="btn-group">
									<label data-text="All" class="glitch-effect">
										<input type="radio" name="fl_radio" value=".box-item" />All
									</label>
								</div>
								{% for category in categories %}
									<div class="btn-group">
										<label data-text="{{ category.name|title }}">
											<input type="radio" name="fl_radio" value=".f-{{ category.name }}" />{{ category.name|title }}
										</label>
									</div>
								{% endfor %}
							{% endif %}
						</div>
					</div>

					<div class="box-items portfolio-items">
						{% if projects %}
							{% for project in projects %}
								<div class="box-item f-{{ project.category }}">
									<div class="image">
										<a href="#popup-{{ forloop.counter }}" class="has-popup-media">
											<img src="{{ project.image.url }}" alt="{{ project.title|title  }}" />
											<span class="info">
												<span class="centrize full-width">
													<span class="vertical-center">
														<span class="ion ion-ios-plus-empty"></span>
													</span>
												</span>
											</span>
										</a>
									</div>
									<div class="desc">
										<div class="category">{{ project.category|title }}</div>
										<a href="#popup-{{ forloop.counter }}" class="name has-popup-media">See More</a>
									</div>
									<div id="popup-{{ forloop.counter }}" class="popup-box mfp-fade mfp-hide">
										<div class="content">
											<div class="image">
												<img src="{{ project.image.url }}" alt="{{ project.title|title }}">
											</div>
											<div class="desc">
												<div class="category">{{ project.category|title }}</div>
												<h4>{{ project.title|title  }}</h4>
												<p>
													{{ project.description }}
												</p>
												<a href="{{ project.link }}" class="btn" data-text="View Project">View Project</a>
											</div>
										</div>
									</div>
								</div>
							{% empty %}
								empty
							{% endfor %}	
						{% endif %}
					</div>
						{% if not projects %}
							<div class="alert-client">
								<p class="alert-text">NO PROJECTS</p>
							</div>
						{% endif %}
					<div class="clear"></div>
				</div>
			</div>
		
		</div>
		
		<!-- Footer -->
		{% social_media %}
		
	</div>
{% endblock %}

portfolio/templates/portfolio/resume.html
{% extends 'base.html' %}
{% load base_tags %}
{% load static %}

{% block title %} | Resume{% endblock %}

{% block content %}
	<!-- Container -->
	<div class="container">
		
		<!-- Header -->
		{% include 'portfolio/partials/nav_header.html' %}
		
		<!-- Wrapper -->
		<div class="wrapper">
		
			<!-- Started -->
			<div class="section started">
				<div class="centrize full-width">
					<div class="vertical-center">
						<div class="started-content">
							<div class="h-title glitch-effect" data-text="Resume">Resume</div>
							<div class="h-subtitle typing-bread">
								<p><a href="{% url 'portfolio:home' %}">Home</a> / <a href="{% url 'portfolio:resume' %}">Resume</a></p>
							</div>
							<span class="typed-bread"></span>
						</div>
					</div>
				</div>
				<a href="#" class="mouse_btn"><span class="ion ion-mouse"></span></a>
			</div>
			
			<!-- About -->
			<div class="section about">
				<div class="content">
					<div class="title">
						<div class="title_inner">About Me</div>
					</div>
					<div class="image">
						<img src="{% static 'portfolio/images/img.png' %}" alt="Yasin Alipour" />
					</div>
					<div class="desc">
						<p>
							{{ user.description }}
						</p>
						<div class="info-list">
							<ul>
								<li><strong>Name:</strong> {{ user.name }}</li>
								<li><strong>Age:</strong> {{ user.age }} Years</li>
								<li><strong>Job:</strong> {{ user.job }}</li>
								<li><strong>E-mail:</strong> {{ user.email }}</li>
							</ul>
						</div>
						<div class="bts"><a href="{{ user.cv_file.url }}" class="btn fill" data-text="Download CV">Download CV</a></div>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			
			<!-- Skills -->
			<div class="section skills">
				<div class="content">
					<div class="title">
						<div class="title_inner">Design Skills</div>
					</div>
					<div class="skills">
						<ul>
							{% for skill in design_skills %}
								<li> 
									<div class="name">{{ skill.title }}</div>
									<div class="progress">
										<div class="percentage" style="width:{{ skill.progress }}%;">
											<span class="percent">{{ skill.progress }}%</span>
										</div>
									</div>
								</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>

			<!-- Skills -->
			<div class="section skills">
				<div class="content">
					<div class="title">
						<div class="title_inner">Coding Skills</div>
					</div>
					<div class="skills circles">
						<ul>
							{% for skill in coding_skills %}
								<li> 
									<div class="name">{{ skill.title }}</div>
									<div class="progress p{{skill.progress}}">
										<div class="percentage" style="width: {{skill.progress}}%;">
											<span class="percent">{{skill.progress}}%</span>
										</div>
										<span>{{skill.progress}}%</span>
									</div>
								</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>

			<!-- Skills -->
			<div class="section skills">
				<div class="content">
					<div class="title">
						<div class="title_inner">Languages Skills</div>
					</div>
					<div class="skills dotted">
						<ul>
							{% for language in languages %}
								<li> 
									<div class="name">{{ language.title }}</div>
									<div class="progress">
										<div class="percentage" style="width: {{ language.progress }}%;">
											<span class="percent">{{ language.progress }}%</span>
										</div>
									</div>
								</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
			
			<!-- Service -->
			<div class="section service">
				<div class="content">
					<div class="title">
						<div class="title_inner">My Services</div>
					</div>
					<div class="service-items">
						{% for service in services %}
							<div class="service-item">
								<div class="icon"><span class="ion ion-{{ service.icon }}"></span></div>
								<div class="name">{{ service.title }}</div>
								<p> {{ service.description }}</p>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
			
			<!-- Clients -->
			<div class="section clients">
				<div class="content">
					<div class="title">
						<div class="title_inner">Clients</div>
					</div>
					<div class="box-items">
						{% if clients %}
							{% for client in clients %}
								<div class="box-item">
									<div class="image">
										<a target="_blank" href="{{ client.link }}">
											<img src="{{ client.image.url }}" alt=" {{ client.title }}" />
											<span class="info">
												<span class="centrize full-width">
													<span class="vertical-center">
														<span class="ion ion-link"></span>
													</span>
												</span>
											</span>
										</a>
									</div>
								</div>
							{% endfor %}
						{% endif %}
					</div>
					{% if not clients %}
						<div class="alert-client">
							<p class="alert-text">NO CLIENTS</p>
						</div>
					{% endif %}
					<div class="clear"></div>
				</div>
			</div>
		
		</div>
		
		<!-- Footer -->
		{% social_media %}
		
	</div>
{% endblock %}