config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', include('portfolio.urls', namespace='portfolio')),
]

if settings.DEBUG:   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dash, name='dash'),

    path('skills/', views.skills_list, name='skills_list'),

    path('designskill/create/', views.DesignSkillCreate.as_view(), name='designskill_create'),
    path('designskill/update/<int:pk>/', views.DesignSkillUpdate.as_view(), name='designskill_update'),
    path('designskill/delete/<int:pk>/', views.DesignSkillDelete.as_view(), name='designskill_delete'),

    path('codingskill/create/', views.CodingSkillCreate.as_view(), name='codingskill_create'),
    path('codingskill/update/<int:pk>/', views.CodingSkillUpdate.as_view(), name='codingskill_update'),
    path('codingskill/delete/<int:pk>/', views.CodingSkillDelete.as_view(), name='codingskill_delete'),

    path('languageskill/create/', views.LanguageSkillCreate.as_view(), name='languageskill_create'),
    path('languageskill/update/<int:pk>/', views.LanguageSkillUpdate.as_view(), name='languageskill_update'),
    path('languageskill/delete/<int:pk>/', views.LanguageSkillDelete.as_view(), name='languageskill_delete'),

    path('messages/', views.message_list, name='message_list'),
    path('message/<pk>/<name>/', views.message_detail, name='message_detail'),

    path('sc/', views.services_clients_list, name='services_clients'),
    path('sc/service/create/', views.ServiceCreate.as_view(), name='service_create'),
    path('sc/service/update/<int:pk>/', views.ServiceUpdate.as_view(), name='service_update'),
    path('sc/service/delete/<int:pk>/', views.ServiceDelete.as_view(), name='service_delete'),

    path('sc/client/create/', views.ClientCreate.as_view(), name='client_create'),
    path('sc/client/update/<int:pk>/', views.ClientUpdate.as_view(), name='client_update'),
    path('sc/client/delete/<int:pk>/', views.ClientDelete.as_view(), name='client_delete'),

    path('projects/', views.project_list, name='project_list'),
    path('projects/category/add/', views.CategoryCreate.as_view(), name='category_add'),
    path('projects/category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category_update'),
    path('projects/category/delete/<int:pk>/', views.CategoryDelete.as_view(), name='category_delete'),

    path('projects/project/add/', views.ProjectAdd.as_view(), name='project_add'),
    path('projects/project/update/<int:pk>/', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/project/delete/<int:pk>/', views.ProjectDelete.as_view(), name='project_delete'),
]

dashboard/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models
from django.urls import reverse

class Resume(models.Model):
    image = models.ImageField(upload_to='resume/image/')
    name = models.CharField(max_length=50, db_index=True)
    age = models.IntegerField()
    job = models.CharField(max_length=100, db_index=True)
    email = models.EmailField(max_length=254)
    cv_file = models.FileField(upload_to='resume/files/')
    description = models.TextField()

    def __str__(self):
        return self.name


class DesignSkill(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class CodingSkill(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class LanguageSkill(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Service(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    description = models.TextField()
    icon = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.title


class Client(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='resume/clients/')

    def __str__(self):
        return self.title



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Project(models.Model):
    category = models.ForeignKey(Category , related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    description = models.TextField()
    image = models.ImageField(upload_to='portfolio/porjects/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return self.title    


class Social(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    link = models.URLField(max_length=200)
    icon = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.title   


class Message(models.Model):
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=254, null=False)
    subject = models.CharField(max_length=100, null=False)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dashboard:message_detail", args=[self.pk, self.name])
    

dashboard/views.py
from django.db.models import fields
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.urls.base import reverse
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


from portfolio.models import Client, DesignSkill, CodingSkill, LanguageSkill, Message, Service, Project, Category

def dash(request):
    if request.user.is_anonymous:
        raise Http404()
    services = Service.objects.all()
    clients = Client.objects.all()
    recent_projects = Project.objects.all().order_by('-id')[:3]
    return render(request, 'dashboard/dashboard.html', {'services': services, 'clients': clients, 'recent_projects': recent_projects})


# Design Skill
class DesignSkillCreate(LoginRequiredMixin, CreateView):
    model = DesignSkill
    fields = ['title', 'progress']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/designskill_form.html'


class DesignSkillUpdate(LoginRequiredMixin, UpdateView):
    model = DesignSkill
    fields = ['title', 'progress']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/designskill_form.html'


class DesignSkillDelete(LoginRequiredMixin, DeleteView):
    model = DesignSkill
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/designskill_confirm_delete.html'


# Coding Skill
class CodingSkillCreate(LoginRequiredMixin, CreateView):
    model = CodingSkill
    fields = ['title', 'progress']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/codingskill_form.html'


class CodingSkillUpdate(LoginRequiredMixin, UpdateView):
    model = CodingSkill
    fields = ['title', 'progress']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/codingskill_form.html'


class CodingSkillDelete(LoginRequiredMixin, DeleteView):
    model = CodingSkill
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/codingskill_confirm_delete.html'


# Language Skill
class LanguageSkillCreate(LoginRequiredMixin, CreateView):
    model = LanguageSkill
    fields = ['title', 'progress']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/languageskill_form.html'


class LanguageSkillUpdate(LoginRequiredMixin, UpdateView):
    model = LanguageSkill
    fields = ['title', 'progress']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/languageskill_form.html'


class LanguageSkillDelete(LoginRequiredMixin, DeleteView):
    model = LanguageSkill
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/skill/languageskill_confirm_delete.html'


def skills_list(request):
    if request.user.is_anonymous:
        raise Http404()
    
    design_skills = DesignSkill.objects.all()
    coding_skills = CodingSkill.objects.all()
    language_skills = LanguageSkill.objects.all()
    return render(request, 'dashboard/skill/skills_list.html', {'design_skills': design_skills, 'coding_skills': coding_skills, 'language_skills': language_skills})

def message_list(request):
    if request.user.is_anonymous:
        raise Http404()
    messages = Message.objects.all().order_by('is_read', '-created')
    return render(request, 'dashboard/message/message_list.html', {'messages': messages})


def message_detail(request, pk, name):
    if request.user.is_anonymous:
        raise Http404()
    message = get_object_or_404(Message, id=pk, name=name)
    message.is_read = True
    message.save()
    return render(request, 'dashboard/message/message_detail.html', {'message': message})


def services_clients_list(request):
    if request.user.is_anonymous:
        raise Http404()
    services = Service.objects.all()
    clients = Client.objects.all()
    return render(request, 'dashboard/services_clients/services_clients.html', {'services': services, 'clients': clients})

class ServiceCreate(LoginRequiredMixin, CreateView):
    model = Service
    fields = ['title', 'description', 'icon']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/services_clients/service_form.html'


class ServiceUpdate(LoginRequiredMixin, UpdateView):
    model = Service
    fields = ['title', 'description', 'icon']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/services_clients/service_form.html'


class ServiceDelete(LoginRequiredMixin, DeleteView):
    model = Service
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/services_clients/service_confirm_delete.html'


class ClientCreate(LoginRequiredMixin, CreateView):
    model = Client
    fields = ['title', 'link', 'image']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/services_clients/client_form.html'


class ClientUpdate(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ['title', 'link', 'image']
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/services_clients/client_form.html'


class ClientDelete(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('dashboard:dash')
    template_name = 'dashboard/services_clients/client_confirm_delete.html'


def project_list(request):
    if request.user.is_anonymous:
        raise Http404()
    projects = Project.objects.all()
    categories = Category.objects.all()
    return render(request, 'dashboard/project/list.html', {'projects': projects, 'categories': categories})

class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('dashboard:project_list')
    template_name = 'dashboard/project/category_form.html'


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('dashboard:project_list')
    template_name = 'dashboard/project/category_form.html'


class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('dashboard:project_list')
    template_name = 'dashboard/project/category_confirm_delete.html'


class ProjectAdd(LoginRequiredMixin, CreateView):
    model = Project
    fields = '__all__'
    success_url = reverse_lazy('dashboard:project_list')
    template_name = 'dashboard/project/project_form.html'


class ProjectUpdate(LoginRequiredMixin, UpdateView):
    model = Project
    fields = '__all__'
    success_url = reverse_lazy('dashboard:project_list')
    template_name = 'dashboard/project/project_form.html'


class ProjectDelete(LoginRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('dashboard:project_list')
    template_name = 'dashboard/project/project_confirm_delete.html'

dashboard/templates/dashboard/skill/codingskill_confirm_delete.html
{% extends 'dashboard/base.html' %}

{% block title %} | Delete {{ object.title }}{% endblock %}

{% block content %}
<main class="main-content mt-0">
    <section>
        <div class="page-header min-vh-75">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 col-md-8 d-flex flex-column mx-auto">
                        <div class="card card-plain">
                            <div class="card-header pb-0 text-center bg-transparent">
                                <h3 class="font-weight-bolder text-info text-gradient">Delete <span class="text-danger text-gradient">{{object.title }}</span></h3>
                            </div>
                            <div class="card-body">
                                <form role="form" method="post">
                                    {% csrf_token %}
                                    <div class="text-center">
                                        <h4>Are you sure you want to delete "{{object.title }}"?</h4>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn bg-gradient-danger w-100 mt-4 mb-0">Delete</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

dashboard/templates/dashboard/skill/codingskill_form.html
{% extends 'dashboard/base.html' %}

{% block title %} | {% if object %} Edit {{object.title }} {% else %} Add Skill{% endif %}{% endblock %}

{% block content %}
<main class="main-content mt-0">
    <section>
        <div class="page-header min-vh-75">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 col-md-8 d-flex flex-column mx-auto">
                        <div class="card card-plain">
                            <div class="card-header pb-0 text-center bg-transparent">
                                <h3 class="font-weight-bolder text-info text-gradient">{% if object %} Edit <span class="text-warning text-gradient">{{object.title }}</span> {% else %} Add Skill{% endif %}</h3>
                            </div>
                            <div class="card-body">
                                <form role="form" method="post">
                                    {% csrf_token %}
                                    <label>Title</label>
                                    <div class="mb-3">
                                        <input type="text" name="title" class="form-control" placeholder="Title" required="" id="id_title" {% if object %}value="{{ object.title }}"{% endif %}>
                                    </div>
                                    <label>Progress</label>
                                    <div class="mb-3">
                                        <input type="number" name="progress" class="form-control" placeholder="Progress" required="" id="id_progress" {% if object %}value="{{ object.progress }}"{% endif %}>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">{% if object %}Edit {% else %} Add{% endif %}</button>
                                    </div>
                                    {% if object %}
                                        <a href="{% url 'dashboard:codingskill_delete' object.pk %}" class="btn bg-gradient-danger w-100 mt-4 mb-0">Delete</a>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

dashboard/templates/dashboard/skill/designskill_confirm_delete.html
{% extends 'dashboard/base.html' %}

{% block title %} | Delete {{ object.title }}{% endblock %}

{% block content %}
<main class="main-content mt-0">
    <section>
        <div class="page-header min-vh-75">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 col-md-8 d-flex flex-column mx-auto">
                        <div class="card card-plain">
                            <div class="card-header pb-0 text-center bg-transparent">
                                <h3 class="font-weight-bolder text-info text-gradient">Delete <span class="text-danger text-gradient">{{object.title }}</span></h3>
                            </div>
                            <div class="card-body">
                                <form role="form" method="post">
                                    {% csrf_token %}
                                    <div class="text-center">
                                        <h4>Are you sure you want to delete "{{object.title }}"?</h4>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn bg-gradient-danger w-100 mt-4 mb-0">Delete</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

dashboard/templates/dashboard/skill/designskill_form.html
{% extends 'dashboard/base.html' %}

{% block title %} | {% if object %} Edit {{object.title }} {% else %} Add Skill{% endif %}{% endblock %}

{% block content %}
<main class="main-content mt-0">
    <section>
        <div class="page-header min-vh-75">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 col-md-8 d-flex flex-column mx-auto">
                        <div class="card card-plain">
                            <div class="card-header pb-0 text-center bg-transparent">
                                <h3 class="font-weight-bolder text-info text-gradient">{% if object %} Edit <span class="text-warning text-gradient">{{object.title }}</span> {% else %} Add Skill{% endif %}</h3>
                            </div>
                            <div class="card-body">
                                <form role="form" method="post">
                                    {% csrf_token %}
                                    <label>Title</label>
                                    <div class="mb-3">
                                        <input type="text" name="title" class="form-control" placeholder="Title" required="" id="id_title" {% if object %}value="{{ object.title }}"{% endif %}>
                                    </div>
                                    <label>Progress</label>
                                    <div class="mb-3">
                                        <input type="number" name="progress" class="form-control" placeholder="Progress" required="" id="id_progress" {% if object %}value="{{ object.progress }}"{% endif %}>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">{% if object %}Edit {% else %} Add{% endif %}</button>
                                    </div>
                                    {% if object %}
                                        <a href="{% url 'dashboard:designskill_delete' object.pk %}" class="btn bg-gradient-danger w-100 mt-4 mb-0">Delete</a>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

dashboard/templates/dashboard/skill/languageskill_confirm_delete.html
{% extends 'dashboard/base.html' %}

{% block title %} | Delete {{ object.title }}{% endblock %}

{% block content %}
<main class="main-content mt-0">
    <section>
        <div class="page-header min-vh-75">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 col-md-8 d-flex flex-column mx-auto">
                        <div class="card card-plain">
                            <div class="card-header pb-0 text-center bg-transparent">
                                <h3 class="font-weight-bolder text-info text-gradient">Delete <span class="text-danger text-gradient">{{object.title }}</span></h3>
                            </div>
                            <div class="card-body">
                                <form role="form" method="post">
                                    {% csrf_token %}
                                    <div class="text-center">
                                        <h4>Are you sure you want to delete "{{object.title }}"?</h4>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn bg-gradient-danger w-100 mt-4 mb-0">Delete</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

dashboard/templates/dashboard/skill/languageskill_form.html
{% extends 'dashboard/base.html' %}

{% block title %} | {% if object %} Edit {{object.title }} {% else %} Add Skill{% endif %}{% endblock %}

{% block content %}
<main class="main-content mt-0">
    <section>
        <div class="page-header min-vh-75">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-7 col-md-8 d-flex flex-column mx-auto">
                        <div class="card card-plain">
                            <div class="card-header pb-0 text-center bg-transparent">
                                <h3 class="font-weight-bolder text-info text-gradient">{% if object %} Edit <span class="text-warning text-gradient">{{object.title }}</span> {% else %} Add Skill{% endif %}</h3>
                            </div>
                            <div class="card-body">
                                <form role="form" method="post">
                                    {% csrf_token %}
                                    <label>Title</label>
                                    <div class="mb-3">
                                        <input type="text" name="title" class="form-control" placeholder="Title" required="" id="id_title" {% if object %}value="{{ object.title }}"{% endif %}>
                                    </div>
                                    <label>Progress</label>
                                    <div class="mb-3">
                                        <input type="number" name="progress" class="form-control" placeholder="Progress" required="" id="id_progress" {% if object %}value="{{ object.progress }}"{% endif %}>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">{% if object %}Edit {% else %} Add{% endif %}</button>
                                    </div>
                                    {% if object %}
                                        <a href="{% url 'dashboard:languageskill_delete' object.pk %}" class="btn bg-gradient-danger w-100 mt-4 mb-0">Delete</a>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}